
export const SEARCH_NO_QUERY = 'SEARCH_REPOS_NO_QUERY';

export const SEARCH_REPOS = 'SEARCH_REPOS';
export const SEARCH_REPOS_OK = 'SEARCH_REPOS_OK';
export const SEARCH_REPOS_FAIL = 'SEARCH_REPOS_FAIL';