export const GET_REPO_REQUEST = 'GET_REPO_REQUEST';
export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS';
export const GET_REPO_FAILURE = 'GET_REPO_FAILURE';

export const GET_LANG_REQUEST = 'GET_LANG_REQUEST';
export const GET_LANG_SUCCESS = 'GET_LANG_SUCCESS';
export const GET_LANG_FAILURE = 'GET_LANG_FAILURE';